### ISSUE TITLE
Change status value to boolean

### ISSUE THREAD

**Issue by ArunBohra12** [ArunBohra12/natours-backend#34]
In the application, where we want to set status for either response from 3rd party API or sending an answer from our server, we use `0 - failed` and `1 - success`.

it might be better to use a boolean instead of these status codes, as true & false are more evident.

**Comment by LogaMithran** [comment]
Hi there, Hope you are doing good.
I'd like to express my interest in working on this issue as my first contribution to open source. Thanks in advance :)

**Comment by ArunBohra12** [comment]
Hello @LogaMithran ,
That's great to hear! Let me know if you need some help getting started. At the moment, we don't have a very good getting started guide but if you find issues with anything just ask for help.
